import {hostText,label as localizedLabel,attribute,t} from './i18n.js';
import {rows,type Frame} from './controller.js';
let panel:HTMLElement|undefined,send:((frame:Frame)=>void)|undefined,state:Frame={},catalog:Frame={},agents:Frame[]=[],message='',pending=false;
let log='',configuration:Frame={};
export function clearExecution():void{panel=undefined;state={};catalog={};agents=[];message='';pending=false;log='';configuration={};}
const run=(command:string,fields:Frame={}):void=>{pending=true;message=t("처리 중…");render();send?.({t:'executionControl',command,fields});};
function render():void {
 if(!panel)return;panel.replaceChildren();const heading=document.createElement('h3');localizedLabel(heading,t("OMP 실행 제어"));panel.append(heading);
 const status=document.createElement('p');status.setAttribute('role','status');localizedLabel(status,message);panel.append(status);
 const version=document.createElement('p');localizedLabel(version,`OMP ${String(catalog['version']??t("조회 중"))} · ${String(catalog['message']??'')}`);panel.append(version);
 const button=(label:string,click:()=>void):void=>{const node=document.createElement('button');node.type='button';node.className='settings-button';localizedLabel(node,label);node.disabled=pending;node.onclick=click;panel!.append(node);};
 button(t("실행 상태 조회"),()=>run('get_state'));button(t("기능·버전 조회"),()=>run('feature_catalog'));
 const toggle=(label:string,command:string,key:string):void=>{const row=document.createElement('label');row.className='settings-field';const caption=document.createElement('span');localizedLabel(caption,label);const select=document.createElement('select');for(const [value,name] of [['',t("조회·선택 필요")],['true',t("사용")],['false',t("사용 안 함")]]){const option=document.createElement('option');option.value=value!;localizedLabel(option,name!);select.append(option);}select.value=typeof state[key]==='boolean'?String(state[key]):'';select.disabled=pending;select.onchange=()=>{if(select.value)run(command,{enabled:select.value==='true'});};row.append(caption,select);panel!.append(row);};
 toggle(t("Fast 모드"),'set_fast_mode','fastModeEnabled');toggle(t("자동 컨텍스트 압축"),'set_auto_compaction','autoCompactionEnabled');toggle(t("자동 재시도"),'set_auto_retry','autoRetryEnabled');
 const choice=(label:string,command:string,key:string,options:string[]):void=>{const row=document.createElement('label');row.className='settings-field';const caption=document.createElement('span');localizedLabel(caption,label);const select=document.createElement('select');for(const value of ['',...options]){const option=document.createElement('option');option.value=value;localizedLabel(option,value||t("선택 필요"));select.append(option);}select.value=String(state[key]??'');select.disabled=pending;select.onchange=()=>{if(select.value)run(command,{mode:select.value});};row.append(caption,select);panel!.append(row);};
 choice(t("캐시 준비"),'set_cache_warming','cacheWarmingMode',['off','streaming','idle']);choice(t("Steering 전달"),'set_steering_mode','steeringMode',['all','one-at-a-time']);choice(t("Follow-up 전달"),'set_follow_up_mode','followUpMode',['all','one-at-a-time']);choice(t("인터럽트 처리"),'set_interrupt_mode','interruptMode',['immediate','wait']);
 const label=document.createElement('label');label.className='settings-field';localizedLabel(label,t("압축 추가 지침 (선택)"));const instructions=document.createElement('textarea');instructions.maxLength=16000;label.append(instructions);panel.append(label);button(t("현재 대화 압축"),()=>run('compact',instructions.value.trim()?{customInstructions:instructions.value}:{}));button(t("재시도 중단"),()=>run('abort_retry'));
 const subheading=document.createElement('h3');localizedLabel(subheading,t("하위 에이전트"));panel.append(subheading);button(t("목록 조회"),()=>run('get_subagents'));
 for(const agent of agents){const row=document.createElement('div');row.className='settings-subagent';const text=document.createElement('p');localizedLabel(text,`${String(agent['agent']??agent['id'])} · ${String(agent['status'])}\n${String(agent['description']??agent['task']??'')}`);row.append(text);const input=document.createElement('textarea');attribute(input,'aria-label',t("하위 에이전트 지시"));input.maxLength=16000;row.append(input);for(const [name,command]of [[t("기록"),'get_subagent_messages'],[t("지시 전달"),'steer_subagent'],[t("중단"),'cancel_subagent']]){const node=document.createElement('button');node.type='button';node.className='settings-button';localizedLabel(node,name!);node.disabled=pending;node.onclick=()=>{if(command==='steer_subagent'&&!input.value.trim())return;run(command!,{subagentId:agent['id'],...(command==='steer_subagent'?{message:input.value}:{})});};row.append(node);}panel.append(row);}
 if(log){const pre=document.createElement('pre');pre.className='settings-agent-log';localizedLabel(pre,log);panel.append(pre);}
 const features=document.createElement('h3');localizedLabel(features,'Advisor · Memory · Prewalk');panel.append(features);button(t("OMP 기능 설정 조회"),()=>run('feature_settings'));
 const scope=document.createElement('p');localizedLabel(scope,String(configuration['scope']??t("실제 OMP가 제공하는 설정만 표시합니다.")));panel.append(scope);
 for(const setting of rows(configuration['settings'])){const row=document.createElement('label');row.className='settings-field';const label=document.createElement('span');localizedLabel(label,String(setting['key']));label.title=String(setting['description']??'');const select=document.createElement('select');for(const [value,name]of [['true',t("사용")],['false',t("사용 안 함")]]){const option=document.createElement('option');option.value=value!;localizedLabel(option,name!);select.append(option);}select.value=String(setting['value']);select.disabled=pending;select.onchange=()=>run('feature_settings',{key:setting['key'],value:select.value==='true',revision:configuration['revision']});row.append(label,select);panel.append(row);}
}
export function executionPanel(action:(frame:Frame)=>void):HTMLElement{send=action;if(!panel){panel=document.createElement('section');panel.className='settings-execution';render();action({t:'executionControl',command:'feature_catalog'});}return panel;}
export function executionResult(command:string,data:Frame,fields:Frame={},error?:string):void {
 pending=false;if(error)message=error;else{message=hostText(data['message']??t("처리했습니다."));if(command==='feature_catalog')catalog=data;else if(command==='feature_settings')configuration=data;else if(command==='get_state')state={...state,...data};else if(command==='get_subagents')agents=rows(data['subagents']);else if(command==='get_subagent_messages')log=rows(data['messages']).map(item=>`${String(item['role']??'agent')}: ${typeof item['content']==='string'?item['content']:rows(item['content']).filter(part=>part['type']==='text').map(part=>String(part['text']??'')).join('\n')}`).join('\n\n')||t("아직 기록이 없습니다.");else if(command==='compact'&&data['accepted']===true){pending=true;message=t("컨텍스트 압축 중…");}else {const keys:Record<string,string>={set_fast_mode:'fastModeEnabled',set_auto_compaction:'autoCompactionEnabled',set_auto_retry:'autoRetryEnabled',set_cache_warming:'cacheWarmingMode',set_steering_mode:'steeringMode',set_follow_up_mode:'followUpMode',set_interrupt_mode:'interruptMode'};const key=keys[command];if(key)state[key]=fields['enabled']??fields['mode'];}}
 render();
}
export function executionEvent(frame:Frame):void{pending=frame['state']==='running';message=frame['state']==='failed'?hostText(frame['message']??t("압축 실패")):pending?t("컨텍스트 압축 중…"):t("컨텍스트 압축을 완료했습니다.");render();}
