import {rows,type Frame} from './controller.js';
let panel:HTMLElement|undefined,send:((frame:Frame)=>void)|undefined,state:Frame={},catalog:Frame={},agents:Frame[]=[],message='',pending=false;
let log='',configuration:Frame={};
export function clearExecution():void{panel=undefined;state={};catalog={};agents=[];message='';pending=false;log='';configuration={};}
const run=(command:string,fields:Frame={}):void=>{pending=true;message='처리 중…';render();send?.({t:'executionControl',command,fields});};
function render():void {
 if(!panel)return;panel.replaceChildren();const heading=document.createElement('h3');heading.textContent='OMP 실행 제어';panel.append(heading);
 const status=document.createElement('p');status.setAttribute('role','status');status.textContent=message;panel.append(status);
 const version=document.createElement('p');version.textContent=`OMP ${String(catalog['version']??'조회 중')} · ${String(catalog['message']??'')}`;panel.append(version);
 const button=(label:string,click:()=>void):void=>{const node=document.createElement('button');node.type='button';node.className='settings-button';node.textContent=label;node.disabled=pending;node.onclick=click;panel!.append(node);};
 button('실행 상태 조회',()=>run('get_state'));button('기능·버전 조회',()=>run('feature_catalog'));
 const toggle=(label:string,command:string,key:string):void=>{const row=document.createElement('label');row.className='settings-field';const caption=document.createElement('span');caption.textContent=label;const select=document.createElement('select');for(const [value,name] of [['','조회·선택 필요'],['true','사용'],['false','사용 안 함']]){const option=document.createElement('option');option.value=value!;option.textContent=name!;select.append(option);}select.value=typeof state[key]==='boolean'?String(state[key]):'';select.disabled=pending;select.onchange=()=>{if(select.value)run(command,{enabled:select.value==='true'});};row.append(caption,select);panel!.append(row);};
 toggle('Fast 모드','set_fast_mode','fastModeEnabled');toggle('자동 컨텍스트 압축','set_auto_compaction','autoCompactionEnabled');toggle('자동 재시도','set_auto_retry','autoRetryEnabled');
 const choice=(label:string,command:string,key:string,options:string[]):void=>{const row=document.createElement('label');row.className='settings-field';const caption=document.createElement('span');caption.textContent=label;const select=document.createElement('select');for(const value of ['',...options]){const option=document.createElement('option');option.value=value;option.textContent=value||'선택 필요';select.append(option);}select.value=String(state[key]??'');select.disabled=pending;select.onchange=()=>{if(select.value)run(command,{mode:select.value});};row.append(caption,select);panel!.append(row);};
 choice('캐시 준비','set_cache_warming','cacheWarmingMode',['off','streaming','idle']);choice('Steering 전달','set_steering_mode','steeringMode',['all','one-at-a-time']);choice('Follow-up 전달','set_follow_up_mode','followUpMode',['all','one-at-a-time']);choice('인터럽트 처리','set_interrupt_mode','interruptMode',['immediate','wait']);
 const label=document.createElement('label');label.className='settings-field';label.textContent='압축 추가 지침 (선택)';const instructions=document.createElement('textarea');instructions.maxLength=16000;label.append(instructions);panel.append(label);button('현재 대화 압축',()=>run('compact',instructions.value.trim()?{customInstructions:instructions.value}:{}));button('재시도 중단',()=>run('abort_retry'));
 const subheading=document.createElement('h3');subheading.textContent='하위 에이전트';panel.append(subheading);button('목록 조회',()=>run('get_subagents'));
 for(const agent of agents){const row=document.createElement('div');row.className='settings-subagent';const text=document.createElement('p');text.textContent=`${String(agent['agent']??agent['id'])} · ${String(agent['status'])}\n${String(agent['description']??agent['task']??'')}`;row.append(text);const input=document.createElement('textarea');input.setAttribute('aria-label','하위 에이전트 지시');input.maxLength=16000;row.append(input);for(const [name,command]of [['기록','get_subagent_messages'],['지시 전달','steer_subagent'],['중단','cancel_subagent']]){const node=document.createElement('button');node.type='button';node.className='settings-button';node.textContent=name!;node.disabled=pending;node.onclick=()=>{if(command==='steer_subagent'&&!input.value.trim())return;run(command!,{subagentId:agent['id'],...(command==='steer_subagent'?{message:input.value}:{})});};row.append(node);}panel.append(row);}
 if(log){const pre=document.createElement('pre');pre.className='settings-agent-log';pre.textContent=log;panel.append(pre);}
 const features=document.createElement('h3');features.textContent='Advisor · Memory · Prewalk';panel.append(features);button('OMP 기능 설정 조회',()=>run('feature_settings'));
 const scope=document.createElement('p');scope.textContent=String(configuration['scope']??'실제 OMP가 제공하는 설정만 표시합니다.');panel.append(scope);
 for(const setting of rows(configuration['settings'])){const row=document.createElement('label');row.className='settings-field';const label=document.createElement('span');label.textContent=String(setting['key']);label.title=String(setting['description']??'');const select=document.createElement('select');for(const [value,name]of [['true','사용'],['false','사용 안 함']]){const option=document.createElement('option');option.value=value!;option.textContent=name!;select.append(option);}select.value=String(setting['value']);select.disabled=pending;select.onchange=()=>run('feature_settings',{key:setting['key'],value:select.value==='true',revision:configuration['revision']});row.append(label,select);panel.append(row);}
}
export function executionPanel(action:(frame:Frame)=>void):HTMLElement{send=action;if(!panel){panel=document.createElement('section');panel.className='settings-execution';render();action({t:'executionControl',command:'feature_catalog'});}return panel;}
export function executionResult(command:string,data:Frame,fields:Frame={},error?:string):void {
 pending=false;if(error)message=error;else{message=String(data['message']??'처리했습니다.');if(command==='feature_catalog')catalog=data;else if(command==='feature_settings')configuration=data;else if(command==='get_state')state={...state,...data};else if(command==='get_subagents')agents=rows(data['subagents']);else if(command==='get_subagent_messages')log=rows(data['messages']).map(item=>`${String(item['role']??'agent')}: ${typeof item['content']==='string'?item['content']:rows(item['content']).filter(part=>part['type']==='text').map(part=>String(part['text']??'')).join('\n')}`).join('\n\n')||'아직 기록이 없습니다.';else if(command==='compact'&&data['accepted']===true){pending=true;message='컨텍스트 압축 중…';}else {const keys:Record<string,string>={set_fast_mode:'fastModeEnabled',set_auto_compaction:'autoCompactionEnabled',set_auto_retry:'autoRetryEnabled',set_cache_warming:'cacheWarmingMode',set_steering_mode:'steeringMode',set_follow_up_mode:'followUpMode',set_interrupt_mode:'interruptMode'};const key=keys[command];if(key)state[key]=fields['enabled']??fields['mode'];}}
 render();
}
export function executionEvent(frame:Frame):void{pending=frame['state']==='running';message=frame['state']==='failed'?String(frame['message']??'압축 실패'):pending?'컨텍스트 압축 중…':'컨텍스트 압축을 완료했습니다.';render();}
