import {hostText,label as localizedLabel,attribute,t} from './i18n.js';
import {object,rows,type Frame} from './controller.js';
let panel:HTMLElement|undefined,snapshot:Frame={},send:((frame:Frame)=>void)|undefined;
let changes:Record<string,string>={},message='',pending=false,scope='global';
export function clearRoles():void{snapshot={};changes={};message='';pending=false;panel=undefined;scope='global';}
const button=(label:string,run:()=>void):HTMLButtonElement=>{const node=document.createElement('button');node.type='button';localizedLabel(node,label);node.className='settings-button';node.disabled=pending;node.onclick=run;return node;};
function render():void{
 if(!panel)return;panel.replaceChildren();const text=document.createElement('p');localizedLabel(text,hostText(snapshot['scope']??t("OMP 역할 설정 조회 중…")));panel.append(text);const status=document.createElement('p');status.setAttribute('role','status');localizedLabel(status,message);panel.append(status);
 panel.append(button(t("다시 조회"),()=>{if(Object.keys(changes).length){message=t("저장하거나 변경 취소 후 다시 조회하세요.");render();return;}pending=true;render();send?.({t:'modelRoles',scope});}));
 const storage=document.createElement('select');attribute(storage,'aria-label',t("역할 저장 위치"));for(const [value,name]of [['global',t("전역")],['project',t("현재 프로젝트")]]){const option=document.createElement('option');option.value=value!;localizedLabel(option,name!);storage.append(option);}storage.value=scope;storage.disabled=pending||Object.keys(changes).length>0;storage.onchange=()=>{scope=storage.value;pending=true;render();send?.({t:'modelRoles',scope});};panel.append(storage);
 const models=rows(snapshot['models']),roles=rows(snapshot['roles']);
 for(const role of roles){const id=String(role['id']),row=document.createElement('div');row.className='settings-role-row';const label=document.createElement('label');localizedLabel(label,String(role['name']??id));const select=document.createElement('select');attribute(select,'aria-label',t("{0} 모델",id));const effort=document.createElement('select');effort.setAttribute('aria-label',`${id} effort`);
  const eligible=models.filter(model=>Array.isArray(role['kinds'])&&role['kinds'].includes(model['kind']));
  const value=changes[id]??String(role['value']??'');const match=eligible.find(model=>value===model['selector']||Array.isArray(model['efforts'])&&model['efforts'].some(level=>value===`${model['selector']}:${level}`));const modelValue=match?String(match['selector']):value;
  const add=(value:string,text:string):void=>{const option=document.createElement('option');option.value=value;localizedLabel(option,text);select.append(option);};
  add('',t("OMP 기본값"));for(const model of eligible)add(String(model['selector']),String(model['name'])+' · '+String(model['selector']));for(const other of roles)if(other['id']!==id)add('@'+String(other['id']),'@'+String(other['id']));if(modelValue&&!Array.from(select.options).some(option=>option.value===modelValue))add(modelValue,modelValue+t(" (현재 설정)"));select.value=modelValue;
  const efforts=():void=>{effort.replaceChildren();const base=document.createElement('option');base.value='';localizedLabel(base,t("OMP 기본 effort"));effort.append(base);const model=eligible.find(model=>model['selector']===select.value);for(const level of Array.isArray(model?.['efforts'])?model['efforts']:[]){const option=document.createElement('option');option.value=String(level);localizedLabel(option,String(level));effort.append(option);}effort.disabled=pending||effort.options.length===1;};efforts();if(match&&value!==modelValue)effort.value=value.slice(modelValue.length+1);
  const change=():void=>{changes[id]=select.value+(effort.value?':'+effort.value:'');message=t("저장 전 변경사항이 있습니다.");localizedLabel(status,message);};select.disabled=pending;select.onchange=()=>{efforts();change();};effort.onchange=change;label.append(select);row.append(label,effort);panel.append(row);
 }
 panel.append(button(t("역할 설정 저장"),()=>{if(!Object.keys(changes).length){message=t("변경사항이 없습니다.");render();return;}pending=true;render();send?.({t:'modelRoles',scope,revision:snapshot['revision'],changes:{...changes}});}),button(t("역할 변경 취소"),()=>{changes={};message=t("변경을 취소했습니다.");render();}));
 const heading=document.createElement('h3');localizedLabel(heading,t("모델 프리셋"));panel.append(heading);const preset=document.createElement('select');attribute(preset,'aria-label',t("저장된 모델 프리셋"));for(const name of Object.keys(object(snapshot['presets']))){const option=document.createElement('option');option.value=name;localizedLabel(option,name);preset.append(option);}preset.disabled=pending;panel.append(preset);const name=document.createElement('input');name.type='text';name.maxLength=80;name.placeholder=t("새 프리셋 이름");attribute(name,'aria-label',t("새 프리셋 이름"));panel.append(name);
 const operation=(op:string,value:string):void=>{if(Object.keys(changes).length){message=t("역할 변경을 먼저 저장하거나 취소하세요.");render();return;}if(!value)return;pending=true;render();send?.({t:'modelRoles',scope,revision:snapshot['revision'],op,name:value});};
 panel.append(button(t("유효 역할을 전역 프리셋으로 저장"),()=>operation('preset_save',name.value.trim())),button(t("선택 프리셋 적용"),()=>operation('preset_apply',preset.value)),button(t("선택 전역 프리셋 삭제"),()=>operation('preset_delete',preset.value)));
}
export function rolesPanel(action:(frame:Frame)=>void):HTMLElement{send=action;if(!panel){panel=document.createElement('div');panel.className='settings-roles';pending=true;render();action({t:'modelRoles'});}return panel;}
export function rolesResult(frame:Frame,error?:string):void{pending=false;if(error)message=error;else{snapshot=frame;if(frame['saved'])changes={};message=hostText(frame['message']??'');}render();}
