using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Web.Script.Serialization;
using Microsoft.Web.WebView2.Core;

internal static class UiSmoke
{
    internal static async Task Run(CoreWebView2 core, Func<Task>? settingsLayout=null)
    {
        var sent=new List<string>();var json=new JavaScriptSerializer();
        core.WebMessageReceived+=(_,args)=>sent.Add(args.WebMessageAsJson);
        // Exercise the shipped page and real browser/CSP, with deterministic host replies.
        for (int i = 0; i < 100; i++) {
            if (await core.ExecuteScriptAsync("document.documentElement.lang !== 'en' && !!window.piagentPost") == "true") break;
            await Task.Delay(50);
        }
        core.PostWebMessageAsJson("{\"type\":\"session\",\"sessionId\":\"smoke\",\"writeEnabled\":true,\"usageEnabled\":false,\"sessionsEnabled\":true,\"transcript\":[{\"role\":\"user\",\"text\":\"<script>bad()</script>\"},{\"role\":\"assistant\",\"text\":\"**원본 UI**\"}]}");
        await Task.Delay(150);
        await Check(core, "document.querySelector('.user-text').textContent === '<script>bad()</script>' && document.querySelector('.markdown-body strong').textContent === '원본 UI'", "history and Markdown");
        await core.ExecuteScriptAsync("ChatActivity.todos([{content:'Task A',status:'completed'},{content:'Task B',status:'in_progress'}]);document.querySelector('#todo-panel summary').click();");
        await Task.Delay(60);
        await Check(core,"!document.querySelector('#todo-panel').open && document.querySelector('#todo-panel summary').textContent.includes('1/2') && localStorage.getItem('piagent.todos.collapsed')==='true'","task list folds to progress summary and remembers preference");
        await core.ExecuteScriptAsync("ChatActivity.todos([{content:'Task A',status:'completed'},{content:'Task B',status:'completed'}]);");
        await Check(core,"!document.querySelector('#todo-panel').open && document.querySelector('#todo-panel summary').textContent.includes('2/2')","live task updates preserve folded state");
        await core.ExecuteScriptAsync("document.querySelector('#todo-panel summary').click();");
        await Task.Delay(60);
        await Check(core,"document.querySelector('#todo-panel').open && document.querySelectorAll('#todo-panel .todo-item').length===2 && document.querySelector('.todo-body').scrollHeight>=document.querySelector('.todo-body').clientHeight","task list expands with bounded body");
        await core.ExecuteScriptAsync("ChatActivity.todos([]);");
        await core.ExecuteScriptAsync("window.gitSmokeActions=[];import('./git.js').then(g=>{window.gitSmoke=g;g.gitStatus({state:'missing',message:'Git 없음'},true,f=>gitSmokeActions.push(f));})");
        await Task.Delay(150);
        await Check(core,"!document.getElementById('git-setup-banner').hidden && document.querySelectorAll('#git-setup-banner button').length===2","non-Git banner offers setup and later");
        await core.ExecuteScriptAsync("document.querySelector('#git-setup-banner button').click();gitSmoke.gitPanel({files:['App.cs','<img src=x>'],excluded:['secrets.json'],ignoreBefore:'# keep',ignoreAfter:'# keep\\nbin/',previewId:'p',revision:'r',message:'Review'});");
        await Check(core,"gitSmokeActions[0].op==='preview' && !document.querySelector('#sheet-body img') && document.querySelectorAll('#sheet-body input').length===2","Git preview uses safe filenames and author fields");
        await core.ExecuteScriptAsync("const a=document.querySelectorAll('#sheet-body input');a[0].value='Test';a[1].value='test@localhost';document.querySelector('#sheet-body button').click();");
        await Check(core,"gitSmokeActions.at(-1).op==='apply' && gitSmokeActions.at(-1).previewId==='p' && gitSmokeActions.at(-1).name==='Test'","first commit is sent only by explicit confirm");
        await core.ExecuteScriptAsync("gitSmoke.gitStatus({state:'ready'},true,()=>{});document.getElementById('sheet').hidden=true;");
        await Check(core,"['Program.cs:3','View.xaml:2','Main.fmx:1','MAIN.PAS:4'].every(text=>{const holder=document.createElement('div');holder.innerHTML=Markdown.render('`'+text+'`');const ref=holder.querySelector('.file-ref');return ref && ref.dataset.path===text.split(':')[0] && ref.dataset.line===text.split(':')[1];}) && !Markdown.linkFileRefs('Unknown.exe:1').includes('file-ref')","IDE-neutral CSharp/XAML/FMX/Pascal file references preserve paths and line numbers");
        core.PostWebMessageAsJson("{\"type\":\"event\",\"data\":{\"sessionId\":\"smoke\",\"turnId\":\"t\",\"sequence\":1,\"kind\":\"started\"}}");
        core.PostWebMessageAsJson("{\"type\":\"event\",\"data\":{\"sessionId\":\"smoke\",\"turnId\":\"t\",\"sequence\":2,\"kind\":\"approval_requested\",\"approval\":{\"proposalId\":\"p\",\"path\":\"A.cs\",\"diff\":\"-old\\n+new\",\"reason\":\"fixture\"}}}");
        await Task.Delay(150);
        await Check(core, "document.querySelector('.approval-card .diff-add').textContent === '+ new' && document.querySelectorAll('.approval-card button').length === 2", "original inline approval card");
        core.PostWebMessageAsJson("{\"type\":\"event\",\"data\":{\"sessionId\":\"smoke\",\"turnId\":\"t\",\"sequence\":3,\"kind\":\"approval_resolved\",\"approval\":{\"approved\":false}}}");
        core.PostWebMessageAsJson("{\"type\":\"event\",\"data\":{\"sessionId\":\"smoke\",\"turnId\":\"t\",\"sequence\":4,\"kind\":\"completed\"}}");
        core.PostWebMessageAsJson("{\"type\":\"sessions\",\"sessions\":[{\"savedSessionId\":\"saved\",\"title\":\"<img src=x onerror=bad()>\",\"resumable\":true,\"updatedAt\":0}]}");
        await Task.Delay(150);
        await Check(core, "!document.getElementById('sheet').hidden && !document.querySelector('#sheet-body img') && document.querySelector('.approval-card.refused') !== null", "session overlay and safe labels");
        sent.Clear();
        core.PostWebMessageAsJson("""{"type":"sessions","sessions":[{"savedSessionId":"empty","title":"<img onerror=bad()>","updatedAt":0,"empty":true,"deletable":true},{"savedSessionId":"used","title":"Used","updatedAt":0,"deletable":false}]}""");
        await Task.Delay(100);
        await Check(core,"document.querySelectorAll('.session-list-row').length===1 && !document.querySelector('#sheet-body img')","empty session delete action and safe label");
        await core.ExecuteScriptAsync("document.querySelector('.session-list-row > button:last-child').click();");
        await Check(core,"document.querySelector('.session-list-row').hidden && document.querySelectorAll('.session-delete-confirm button').length===2","empty session deletion requires confirmation");
        await core.ExecuteScriptAsync("document.querySelector('.session-delete-confirm button:last-child').click();");
        if(sent.Exists(message=>message.Contains("\"action\":\"deleteEmptySession\"")))throw new Exception("Cancelled deletion reached host");
        await Check(core,"!document.querySelector('.session-delete-confirm') && !document.querySelector('.session-list-row').hidden","cancel preserves empty session");
        await core.ExecuteScriptAsync("document.querySelector('.session-list-row > button:last-child').click();document.querySelector('.session-delete-confirm button').click();");
        await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"action\":\"deleteEmptySession\"")&&message.Contains("\"confirmed\":true")))throw new Exception("Confirmed deletion did not reach host");
        core.PostWebMessageAsJson("""{"type":"sessionDeleted","savedSessionId":"empty"}""");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"action\":\"listSessions\"")))throw new Exception("Deleted session list did not refresh");
        await Check(core,"!document.getElementById('sheet').hidden","session deletion keeps session list accessible");
        core.PostWebMessageAsJson("""{"type":"session","sessionId":"native","ompControlsEnabled":true,"ompProfile":"native"}""");
        core.PostWebMessageAsJson("""{"type":"ompControl","command":"get_available_models","data":{"models":[{"provider":"fixture","id":"model","name":"Model"}]}}""");
        core.PostWebMessageAsJson("""{"type":"ompControl","command":"get_available_thinking_levels","data":{"levels":["off","high"]}}""");
        await Task.Delay(150);
        await Check(core, "!document.getElementById('model-btn').disabled && !document.getElementById('thinking-select').disabled", "negotiated original model/effort controls enabled");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"native","sequence":1,"kind":"omp_event","frame":{"type":"extension_ui_request","method":"confirm","id":"confirm","title":"<img onerror=bad()>","message":"Confirm fixture"}}}""");
        await Task.Delay(150);
        await Check(core, "document.querySelectorAll('.action-card .card-btn').length === 3 && !document.querySelector('.action-card img')", "safe OMP confirmation card");
        core.PostWebMessageAsJson("""{"type":"disconnected"}""");
        await Task.Delay(150);
        await Check(core, "!document.querySelector('.action-card')", "expired interaction removed on disconnect");
        await Check(core,"document.getElementById('model-btn').disabled && document.getElementById('thinking-select').disabled","disconnect disables stale capabilities");
        core.PostWebMessageAsJson("""{"type":"session","sessionId":"complete","savedSessionId":"stable","transcript":[{"role":"user","text":"Preserved conversation"}],"btwEnabled":true,"preferencesEnabled":true,"attachmentsEnabled":true,"exportEnabled":true,"ompControlsEnabled":true,"ompProfile":"native"}""");
        await Task.Delay(150);
        await Check(core,"!document.getElementById('btw-btn').disabled && !document.getElementById('export-btn').disabled && !document.getElementById('plus-btn').disabled","new capabilities enable original controls");
        sent.Clear();
        await core.ExecuteScriptAsync("document.getElementById('sheet').hidden=true;ChatComposer.setInput('/btw 별도 질문');document.getElementById('send-btn').click();");
        await Task.Delay(100);
        var question=sent.Find(message=>message.Contains("\"action\":\"btw\""))??throw new Exception("BTW composer did not reach host");
        var request=json.Deserialize<Dictionary<string,object>>(question);var id=request["id"];
        core.PostWebMessageAsJson(json.Serialize(new {type="operationError",action="btw",id,message="fixture failure"}));
        await Task.Delay(100);await Check(core,"document.getElementById('input').value === '/btw 별도 질문'","BTW error keeps draft");
        sent.Clear();await core.ExecuteScriptAsync("document.getElementById('send-btn').click();");await Task.Delay(100);
        request=json.Deserialize<Dictionary<string,object>>(sent.Find(message=>message.Contains("\"action\":\"btw\""))!);
        core.PostWebMessageAsJson(json.Serialize(new {type="btwAccepted",id=request["id"]}));await Task.Delay(100);
        await Check(core,"document.getElementById('input').value === ''","BTW accepted clears acknowledged draft");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"complete","sequence":1,"kind":"omp_event","frame":{"type":"ui_event","event":{"t":"btw","turn":0,"topic":{"id":"topic","mainSession":"stable","mainTitle":"Fixture","created":"now","turns":[{"q":"별도 질문","a":"답변","state":"done","asked":"now"}]}}}}}""");
        await Task.Delay(100);await Check(core,"document.querySelector('.btw-card .btw-answer').textContent.includes('답변')","BTW answer uses original folded card");
        sent.Clear();await core.ExecuteScriptAsync("document.getElementById('btw-btn').click();");await Task.Delay(100);
        await Check(core,"!document.getElementById('btw-panel').hidden","BTW button opens notes");
        if(!sent.Exists(message=>message.Contains("\"action\":\"btwList\"")))throw new Exception("BTW notes did not request list");
        sent.Clear();await core.ExecuteScriptAsync("const side=document.getElementById('btw-new-input');side.value='노트 질문';side.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));");await Task.Delay(100);
        request=json.Deserialize<Dictionary<string,object>>(sent.Find(message=>message.Contains("\"action\":\"btw\""))!);
        await Check(core,"document.getElementById('btw-new-input').disabled && document.getElementById('btw-new-input').value==='노트 질문'","BTW notes wait for acknowledgement");
        core.PostWebMessageAsJson(json.Serialize(new {type="operationError",action="btw",id=request["id"],message="side failed"}));await Task.Delay(100);
        await Check(core,"!document.getElementById('btw-new-input').disabled && document.getElementById('btw-new-input').value==='노트 질문'","BTW notes failure keeps draft");
        await core.ExecuteScriptAsync("ChatBtw.close();document.getElementById('settings-btn').click();");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"action\":\"preferences\"")))throw new Exception("Settings did not request preferences");
        core.PostWebMessageAsJson("""{"type":"preferences","piagentVersion":"0.9.13","values":{"language":"ko","fontSize":13,"showThinking":true,"showTools":true,"showTodos":true,"showSubagents":true,"notifications":false,"highContrast":false,"defaultApproval":"always-ask"},"ompExecutable":"fixture","ompProfile":"native"}""");
        await Task.Delay(150);await Check(core,"document.querySelectorAll('[role=tab]').length === 5 && !document.getElementById('sheet').hidden","settings preserves five original areas");
        await Check(core,"document.querySelector('.settings-about').textContent.includes('PiAgent 0.9.13') && document.querySelector('.settings-about').textContent.includes('김민걸 (Min-Gul Kim)') && document.querySelector('.settings-about').textContent.includes('mgkim@jbnu.ac.kr')","settings shows actual version and developer identity");
        await core.ExecuteScriptAsync("document.querySelector('input[type=number]').value='16';document.querySelector('input[type=number]').dispatchEvent(new Event('change'));document.getElementById('settings-tab-1').click();Array.from(document.querySelectorAll('.settings-content button')).find(b=>b.textContent==='로그인 제공자 상태').click();document.getElementById('settings-tab-4').click();");
        await Task.Delay(100);if(!sent.Exists(message=>message.Contains("get_login_providers")))throw new Exception("Account status did not request providers");
        core.PostWebMessageAsJson("""{"type":"ompControl","command":"get_login_providers","data":{"providers":[{"id":"fixture","name":"Fixture provider","available":true,"authenticated":true}]}}""");await Task.Delay(100);
        await Check(core,"document.getElementById('sheet-title').textContent==='PiAgent 설정' && document.querySelectorAll('[role=tab]').length===5 && document.getElementById('settings-tab-4').getAttribute('aria-selected')==='true'","late provider result preserves settings navigation and selected tab");
        await core.ExecuteScriptAsync("document.getElementById('settings-tab-1').click()");
        await Check(core,"document.querySelector('.settings-account-status').textContent.includes('Fixture provider: 로그인됨') && document.querySelector('.settings-actions')!==null","provider status renders inside account tab with footer intact");
        sent.Clear();await core.ExecuteScriptAsync("document.querySelector('.settings-providers button').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"command\":\"login\"")&&message.Contains("fixture")))throw new Exception("Account login button did not reach host");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"complete","sequence":2,"kind":"omp_event","frame":{"type":"login_status","state":"pending"}}}""");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"complete","sequence":3,"kind":"omp_event","frame":{"type":"extension_ui_request","login":true,"id":"login:fixture:code","method":"input","title":"인증 코드"}}}""");await Task.Delay(100);
        await Check(core,"document.querySelectorAll('[role=tab]').length===5 && document.querySelector('.settings-login-card input')!==null && !document.querySelector('#log .settings-login-card')","OAuth input stays inside account tab");
        await core.ExecuteScriptAsync("document.querySelector('.settings-login-card input').value='fixture-code';Array.from(document.querySelectorAll('.settings-login-card button')).find(b=>b.textContent==='제출').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("ompRespond")&&message.Contains("fixture-code")))throw new Exception("OAuth code did not reach host");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"complete","sequence":4,"kind":"omp_event","frame":{"type":"login_status","state":"completed"}}}""");await Task.Delay(100);
        await Check(core,"document.querySelector('.settings-account-status').textContent.includes('로그인했습니다.') && !document.querySelector('.settings-login-card')","OAuth completion clears input and preserves settings");
        await core.ExecuteScriptAsync("document.getElementById('settings-tab-0').click()");
        await Check(core,"document.querySelector('input[type=number]').value==='16'","provider lookup preserves unsaved preferences");
        await core.ExecuteScriptAsync("document.getElementById('settings-tab-0').dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));");
        await Check(core,"document.getElementById('settings-tab-4').getAttribute('aria-selected')==='true' && document.activeElement.id==='settings-tab-4' && document.querySelector('.settings-content').textContent.includes('mgkim@jbnu.ac.kr')","keyboard tabs expose developer information in Advanced");
        core.PostWebMessageAsJson("""{"type":"ompControl","command":"feature_catalog","data":{"version":"18.6.1","verifiedContract":true,"message":"verified fixture"}}""");await Task.Delay(100);
        await Check(core,"document.querySelector('.settings-execution').textContent.includes('18.6.1') && document.querySelectorAll('[role=tab]').length===5","execution catalogue preserves five original settings tabs");
        sent.Clear();await core.ExecuteScriptAsync("Array.from(document.querySelectorAll('.settings-execution button')).find(b=>b.textContent==='목록 조회').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("get_subagents")))throw new Exception("Subagents did not reach Core");
        core.PostWebMessageAsJson("""{"type":"ompControl","command":"get_subagents","data":{"subagents":[{"id":"agent-1","agent":"scout","status":"running","description":"Fixture"}]}}""");await Task.Delay(100);
        await Check(core,"document.querySelector('.settings-subagent').textContent.includes('scout')","subagent snapshot renders inside Advanced");
        sent.Clear();await core.ExecuteScriptAsync("Array.from(document.querySelectorAll('.settings-subagent button')).find(b=>b.textContent==='기록').click()");await Task.Delay(100);
        core.PostWebMessageAsJson("""{"type":"ompControl","command":"get_subagent_messages","data":{"messages":[{"role":"assistant","content":"<script>fixture log</script>"}]}}""");await Task.Delay(100);
        await Check(core,"document.querySelector('.settings-agent-log').textContent.includes('<script>fixture log</script>') && document.querySelectorAll('[role=tab]').length===5 && document.getElementById('sheet-title').textContent==='PiAgent 설정'","subagent logs escape HTML and keep settings navigation");
        sent.Clear();await core.ExecuteScriptAsync("document.getElementById('settings-tab-2').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("model_roles")))throw new Exception("Role tab did not query OMP");
        core.PostWebMessageAsJson("""{"type":"ompControl","command":"model_roles","data":{"revision":"fixture","scope":"OMP 전역 설정","roles":[{"id":"slow","kinds":["chat"],"value":"fixture/model:low"}],"models":[{"selector":"fixture/model","name":"Fixture","kind":"chat","efforts":["low","high"]}]}}""");await Task.Delay(100);
        await Check(core,"Array.from(document.querySelector('[aria-label=\"slow effort\"]').options).map(o=>o.value).join(',')===',low,high'","role effort choices come from OMP model catalogue");
        sent.Clear();await core.ExecuteScriptAsync("const effort=document.querySelector('[aria-label=\"slow effort\"]');effort.value='high';effort.dispatchEvent(new Event('change'));Array.from(document.querySelectorAll('.settings-roles button')).find(b=>b.textContent==='역할 설정 저장').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("fixture/model:high")&&message.Contains("model_roles")))throw new Exception("Role save did not reach Core");
        core.PostWebMessageAsJson("""{"type":"operationError","action":"ompControl","command":"model_roles","message":"fixture stale settings"}""");await Task.Delay(100);
        await Check(core,"document.querySelector('.settings-roles').textContent.includes('stale settings') && document.querySelectorAll('[role=tab]').length===5","role save error preserves settings tabs");
        await core.ExecuteScriptAsync("document.getElementById('settings-tab-0').click()");
        await core.ExecuteScriptAsync("document.getElementById('scroll-bottom-btn').classList.add('visible')");
        await Check(core,"getComputedStyle(document.getElementById('scroll-bottom-btn')).display==='none' && !document.getElementById('sheet').hidden","settings sheet hides the floating new-message button");
        if(settingsLayout!=null)await settingsLayout();
        await Check(core,"document.getElementById('title-btn').textContent.includes('Preserved conversation') && document.getElementById('conn-dot').title !== '연결 중'","translation refresh preserves conversation title and live connection state: "+await core.ExecuteScriptAsync("JSON.stringify({title:document.getElementById('title-btn').textContent,state:document.getElementById('conn-dot').title})"));
        sent.Clear();await core.ExecuteScriptAsync("const font=document.querySelector('#sheet-body input[type=number]');font.value='17';font.dispatchEvent(new Event('change'));Array.from(document.querySelectorAll('#sheet-body button')).find(b=>b.textContent==='적용').click();");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"fontSize\":17")))throw new Exception("Settings apply did not reach host");
        core.PostWebMessageAsJson("""{"type":"operationError","action":"preferences","message":"fixture disk full"}""");await Task.Delay(100);
        await Check(core,"!document.getElementById('sheet').hidden && document.querySelector('#sheet-body [role=status]').textContent.includes('disk full')","settings save failure keeps sheet open");
        sent.Clear();await core.ExecuteScriptAsync("Array.from(document.querySelectorAll('.settings-actions button')).find(b=>b.textContent==='저장하고 닫기').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"fontSize\":17")))throw new Exception("Save and close did not reach host");
        core.PostWebMessageAsJson("""{"type":"preferences","piagentVersion":"0.9.13","values":{"language":"ko","fontSize":17}}""");await Task.Delay(150);
        await Check(core,"document.getElementById('sheet').hidden","save and close waits for successful host acknowledgement");
        await core.ExecuteScriptAsync("document.getElementById('settings-btn').click()");await Task.Delay(100);
        core.PostWebMessageAsJson("""{"type":"preferences","piagentVersion":"0.9.13","values":{"language":"ko","fontSize":17}}""");await Task.Delay(100);
        sent.Clear();await core.ExecuteScriptAsync("document.querySelector('.settings-field input[type=number]').value='23';document.querySelector('.settings-field input[type=number]').dispatchEvent(new Event('change'));Array.from(document.querySelectorAll('.settings-actions button')).find(b=>b.textContent==='취소').click()");await Task.Delay(100);
        if(sent.Exists(message=>message.Contains("\"action\":\"preferences\"")))throw new Exception("Cancel wrote preferences");
        await Check(core,"document.getElementById('sheet').hidden","cancel closes without saving local edits");
        sent.Clear();await core.ExecuteScriptAsync("document.getElementById('sheet').hidden=true;ChatComposer.setInput('@Main');document.getElementById('input').dispatchEvent(new Event('input'));");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"action\":\"listFiles\"")))throw new Exception("@ completion did not request workspace files");
        core.PostWebMessageAsJson("""{"type":"files","items":["Main.cs","Main.xaml"]}""");await Task.Delay(100);
        await Check(core,"document.getElementById('slash-menu').textContent.includes('Main.cs')","@ completion renders returned files");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"complete","turnId":"busy","sequence":10,"kind":"started"}}""");
        core.PostWebMessageAsJson("""{"type":"preferences","values":{"language":"ko","fontSize":13}}""");await Task.Delay(200);
        await Check(core,"document.getElementById('approval-select').disabled && document.getElementById('model-btn').disabled && document.getElementById('input').placeholder.includes('omp 작업 중') && document.getElementById('input').value === '@Main'","translation refresh preserves busy capability gates and draft");
        core.PostWebMessageAsJson("""{"type":"session","sessionId":"plan-check","approvalMode":"plan","transcript":[{"role":"event","text":"","event":{"t":"plan","path":"docs/plans/fixture.md","title":"Fixture plan"}}]}""");await Task.Delay(100);
        sent.Clear();await core.ExecuteScriptAsync("document.querySelector('.plan-card button').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"action\":\"proceedPlan\"")))throw new Exception("Plan action did not reach host");
        core.PostWebMessageAsJson("""{"type":"operationError","action":"proceedPlan","message":"Plan changed after preview"}""");await Task.Delay(100);
        await Check(core,"document.querySelector('.plan-card .card-status').textContent === 'Plan changed after preview' && Array.from(document.querySelectorAll('.plan-card button')).every(b=>!b.disabled)","plan failure displays error and restores original card actions");
        core.PostWebMessageAsJson("""{"type":"session","sessionId":"timeline","messageRestoreEnabled":true,"transcript":[{"role":"user","text":"before message","seq":1}]}""");await Task.Delay(100);
        await Check(core,"document.querySelectorAll('.cp-btn').length === 2","message history restores original hover actions");
        sent.Clear();await core.ExecuteScriptAsync("document.querySelectorAll('.cp-btn')[1].click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"action\":\"previewMessageRestore\"")&&message.Contains("\"branch\":true")))throw new Exception("Message branch did not preview");
        core.PostWebMessageAsJson("""{"type":"messageRestorePreview","data":{"messageRestoreId":"timeline-preview","revision":"revision","files":[],"reason":"Conversation snapshot; original preserved","diff":""}}""");await Task.Delay(100);
        await Check(core,"document.querySelector('.approval-card').textContent.includes('original preserved')","message restore requires original inline review");
        sent.Clear();await core.ExecuteScriptAsync("document.querySelector('.approval-card button').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"action\":\"restoreMessage\"")&&message.Contains("timeline-preview")))throw new Exception("Message restore approval did not reach host");
        core.PostWebMessageAsJson("""{"type":"session","sessionId":"branch","messageRestoreEnabled":true,"transcript":[],"restoredDraft":"before message","restoreNotice":"Original preserved"}""");await Task.Delay(100);
        await Check(core,"document.getElementById('input').value === 'before message' && !document.querySelector('.turn-user')","restore returns draft without submitting or retaining discarded turns");
        core.PostWebMessageAsJson("""{"type":"session","sessionId":"conditional","savedSessionId":"conditional-saved","ompControlsEnabled":true,"ompProfile":"native","btwEnabled":true}""");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"conditional","sequence":1,"kind":"omp_event","frame":{"type":"ui_event","event":{"t":"notice","level":"retry","text":"Deterministic provider retry fixture"}}}}""");
        await Task.Delay(100);
        await Check(core,"document.querySelectorAll('.retry-cancel').length===1","provider retry exposes the original cancel control");
        sent.Clear();await core.ExecuteScriptAsync("document.querySelector('.retry-cancel').click()");await Task.Delay(100);
        if(!sent.Exists(message=>message.Contains("\"command\":\"abort_retry\"")))throw new Exception("Retry cancellation did not reach the host");
        await Check(core,"!document.querySelector('.retry-cancel')","retry cancellation reaches native control once and removes the button");
        core.PostWebMessageAsJson("""{"type":"session","sessionId":"long-running"}""");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"long-running","turnId":"long","sequence":1,"kind":"started"}}""");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"long-running","turnId":"long","sequence":2,"kind":"activity","text":"하위 에이전트 작업 중","frame":{"elapsedMs":661000}}}""");await Task.Delay(100);
        await Check(core,"!document.getElementById('working').hidden && document.querySelector('#working .working-text').textContent.includes('하위 에이전트 작업 중 · 11분 1초')","long-running activity remains busy beyond ten minutes");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"long-running","turnId":"long","sequence":3,"kind":"error","text":"OMP 프로세스가 예기치 않게 종료되었습니다."}}""");
        core.PostWebMessageAsJson("""{"type":"event","data":{"sessionId":"long-running","turnId":null,"sequence":4,"kind":"closed","text":"OMP 프로세스가 예기치 않게 종료되었습니다."}}""");await Task.Delay(100);
        await Check(core,"!document.getElementById('banner').hidden && document.getElementById('banner').textContent.includes('OMP 프로세스') && document.getElementById('log').textContent.includes('OMP 프로세스')","session closure preserves failure reason in status and conversation");
        await Check(core, "smokeErrors.length === 0", "no JavaScript or CSP errors: " + await core.ExecuteScriptAsync("smokeErrors"));
        await core.ExecuteScriptAsync("document.getElementById('sheet').hidden=true;window.marker=42;ChatComposer.setInput('도킹 전 초안');");
    }
    private static async Task Check(CoreWebView2 core, string script, string name)
    {
        var result = await core.ExecuteScriptAsync(script);
        if (result != "true") throw new Exception(name + ": " + result + " · browser errors: " + await core.ExecuteScriptAsync("JSON.stringify(window.smokeErrors || [])"));
        Console.WriteLine("PASS: " + name);
    }
}
